title: Willy London
description: The Creative Technician
url: https://www.thecreativetechnician.online
default_post_image: /assets/images/default-post-cover.svg
default_post_image_width: 1200
default_post_image_height: 630
markdown: kramdown
theme: null

permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
